import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.scss";
import { getServerSession } from "next-auth";
import SessionProvider from "./providers/SessionProvider";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"], // Add the weights you want to use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="https://cdn.conekta.io/js/latest/conekta.js"
        ></script>
      </head>
      <body className={montserrat.className}>
        <Toaster />
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
